project_id = "wmuwctsmuagetcjqeboz"

[functions.asaas-webhook]
verify_jwt = false

[functions.toggle-event-certificates]
verify_jwt = true

[functions.signup-direct]
verify_jwt = false

[functions.ensure-user-profile]
verify_jwt = false

[functions.become-producer]
verify_jwt = false